package com.tuarua.firebase.analytics {
public final class FirebaseAnalyticsParam {
    public static const ACHIEVEMENT_ID:String = "achievement_id";
    public static const CHARACTER:String = "character";
    public static const TRAVEL_CLASS:String = "travel_class";
    public static const CONTENT_TYPE:String = "content_type";
    public static const CURRENCY:String = "currency";
    public static const COUPON:String = "coupon";
    public static const START_DATE:String = "start_date";
    public static const END_DATE:String = "end_date";
    public static const FLIGHT_NUMBER:String = "flight_number";
    public static const GROUP_ID:String = "group_id";
    public static const ITEM_CATEGORY:String = "item_category";
    public static const ITEM_ID:String = "item_id";
    /** @deprecated Instead, use LOCATION_ID */
    public static const ITEM_LOCATION_ID:String = "item_location_id";
    public static const ITEM_NAME:String = "item_name";
    public static const LOCATION:String = "location";
    public static const LEVEL:String = "level";
    public static const SIGN_UP_METHOD:String = "sign_up_method";
    public static const NUMBER_OF_NIGHTS:String = "number_of_nights";
    public static const NUMBER_OF_PASSENGERS:String = "number_of_passengers";
    public static const NUMBER_OF_ROOMS:String = "number_of_rooms";
    public static const DESTINATION:String = "destination";
    public static const ORIGIN:String = "origin";
    public static const PRICE:String = "price";
    public static const QUANTITY:String = "quantity";
    public static const SCORE:String = "score";
    public static const SCREEN_CLASS:String = "screen_class";
    public static const SCREEN_NAME:String = "screen_name";
    public static const SHIPPING:String = "shipping";
    public static const TRANSACTION_ID:String = "transaction_id";
    public static const SEARCH_TERM:String = "search_term";
    public static const TAX:String = "tax";
    public static const VALUE:String = "value";
    public static const VIRTUAL_CURRENCY_NAME:String = "virtual_currency_name";
    public static const CAMPAIGN:String = "campaign";
    public static const SOURCE:String = "source";
    public static const MEDIUM:String = "medium";
    public static const TERM:String = "term";
    public static const CONTENT:String = "content";
    public static const ACLID:String = "aclid";
    public static const CP1:String = "cp1";
    public static const ITEM_BRAND:String = "item_brand";
    public static const ITEM_VARIANT:String = "item_variant";
    /** @deprecated Instead, use ITEM_LIST_NAME */
    public static const ITEM_LIST:String = "item_list";
    /** @deprecated Instead, use CHECKOUT_OPTION */
    public static const CHECKOUT_STEP:String = "checkout_step";
    public static const CHECKOUT_OPTION:String = "checkout_option";
    public static const CREATIVE_NAME:String = "creative_name";
    public static const CREATIVE_SLOT:String = "creative_slot";
    public static const AFFILIATION:String = "affiliation";
    public static const INDEX:String = "index";
    public static const DISCOUNT:String = "discount";
    public static const ITEM_CATEGORY2:String = "item_category2";
    public static const ITEM_CATEGORY3:String = "item_category3";
    public static const ITEM_CATEGORY4:String = "item_category4";
    public static const ITEM_CATEGORY5:String = "item_category5";
    public static const ITEM_LIST_ID:String = "item_list_id";
    public static const ITEM_LIST_NAME:String = "item_list_name";
    public static const ITEMS:String = "items";
    public static const LOCATION_ID:String = "location_id";
    public static const PAYMENT_TYPE:String = "payment_type";
    public static const PROMOTION_ID:String = "promotion_id";
    public static const PROMOTION_NAME:String = "promotion_name";
    public static const SHIPPING_TIER:String = "shipping_tier";
}
}
